Add custom function for dark-light modes
fernandoox/weather-app pull request #4
Opened 2022-06-23 07:22 UTC by oscarmtl7

**Purpose**

Add the function dark-light to the App using css

Aproach

-I add the dark-light functionality via css.

-I also made the theme user preference to be stored in localstorage
image

Where should the reviewer start?
In App.ts we have the <DarkMode/> component that have the toggle botton and the logic for save the user selection in localstorage and in their css file src\component\DarkMode.tsx.

This PR addresses a:

- [ ] Bug
- [x] Feature
- [ ] Technical Debt
- [ ] Chore
- [ ] Vulnerability

2022-06-24 03:21 UTC, fernandoox requested changes

2022-06-24 03:21 UTC, fernandoox commented on src/css/DarkMode.css
> +:root {
We have to use scss files instead of css, also we decided to use with BEM, look this http://getbem.com/introduction/

2022-06-24 03:21 UTC, fernandoox commented on src/component/DarkMode.tsx
> +          // 6
please, remove unused comments

2022-06-24 03:21 UTC, fernandoox commented on src/App.css
> +  /* background-color: #282c34; */
remove unnecessary comments 🙂

2022-06-24 03:21 UTC, fernandoox commented on src/App.tsx
>  import './App.css';
a good practice is import styles at the end of the imports

2022-06-24 18:07 UTC, fernandoox commented
**I forgot something, now we're developing functional features so we need to write unit tests** 🧪 @oscarmtl7 @ticsaul @jakirock4

2022-06-25 14:36 UTC, ticsaul approved these changes
I don't have comments.

2022-06-25 19:22 UTC, jakirock4 requested changes
I see the same recommendations as @fernandoox.
please fix it

2022-07-07 13:30 UTC, ticsaul approved these changes
It's OK

2022-07-08 16:05 UTC, fernandoox commented
You need to rebase the branch `main` to fix the `yarn.lock` also there aren't unit tests. 😢 @oscarmtl7

2022-07-11 16:51 UTC, fernandoox approved these changes

2022-07-11 16:51 UTC, fernandoox commented on src/index.tsx
> +import './index.css';
Maybe scss instead of css

2022-07-11 19:37 UTC, merged