chore: add unit test to weather api
fernandoox/weather-app pull request #6
Opened 2022-06-28 02:50 UTC by fernandoox

## Purpose
It's necessary to improve our coverage :chart_with_upwards_trend: 

## Approach
- I moved the file weatherApi.ts
- I wrote the unit test for the file 👆️
![image](https://user-images.githubusercontent.com/43055981/176081140-c69028f8-e51f-4e2f-a47c-49c6ee44e93a.png)
![image](https://user-images.githubusercontent.com/43055981/176081256-b12485c5-5b7c-4752-bafb-2141c91b4473.png)
## Where should the reviewer start?
Unit Test

## This PR addresses a:
- [ ] Bug
- [ ] Feature
- [X] Technical Debt
- [ ] Chore
- [ ] Vulnerability

2022-06-28 14:59 UTC, ticsaul commented on tsconfig.json
> +    "jsx": "react-jsx",
I think you should remove this comma

2022-06-28 15:26 UTC, ticsaul commented on .idea/inspectionProfiles/Project_Default.xml
> +    <inspection_tool class="SpellCheckingInspection" enabled="false" level="TYPO" enabled_by_default="false">
Is neccesary this file ?

2022-06-28 15:26 UTC, ticsaul requested changes
I write comments in some files.

2022-06-29 02:21 UTC, fernandoox commented on tsconfig.json
> +    "jsx": "react-jsx",
I ran the prettier, done

2022-07-07 03:08 UTC, ticsaul approved these changes
Ok

2022-07-11 01:16 UTC, oscarmtl7 reviewed
It´s okay, only can you check the yarn file, i think have it conflict

2022-07-11 17:41 UTC, merged